name: Swift

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Swift version
  # You may pin to the exact commit or the version.
  # uses: sersoft-gmbh/swift-version-action@f05fc577db170ebe6991af280f060227d21d1bb0
      uses: sersoft-gmbh/swift-version-action@v1.0.0
    - name: GitHub Action for SwiftLint
  # You may pin to the exact commit or the version.
  # uses: norio-nomura/action-swiftlint@9f4dcd7fd46b4e75d7935cf2f4df406d5cae3684
      uses: norio-nomura/action-swiftlint@3.2.1
