name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Xcode Build
  # You may pin to the exact commit or the version.
  # uses: devbotsxyz/xcode-build@2138f429e7bebe426d65985aca0dbad5370aa697
      uses: devbotsxyz/xcode-build@v1.0.0
