name: CI

on: [push] # git push をトリガーとする

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v1 # ソースコードをcheckout
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_13.0.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
   # - name: Build # シミュレーター向けにビルド
   #   run: xcodebuild -sdk iphonesimulator -configuration Debug build 
