name: Swift

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Swift version
  # You may pin to the exact commit or the version.
  # uses: sersoft-gmbh/swift-version-action@f05fc577db170ebe6991af280f060227d21d1bb0
      uses: sersoft-gmbh/swift-version-action@v1.0.0
      
    - uses: actions/checkout@v1 # ソースコードをcheckout
    - name: Select Xcode version # Xcode 12.4 を使う
      run: sudo xcode-select -s '/Applications/Xcode_12.4.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Build # シミュレーター向けにビルド
      run: xcodebuild -sdk iphonesimulator -configuration Debug build 
